"""add updated_at column to all tables

Revision ID: 0f367b918bba
Revises: 11e57ae7f10c
Create Date: 2026-03-27 12:36:43.009082

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f367b918bba'
down_revision: str | Sequence[str] | None = '11e57ae7f10c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'bookable_units',
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
    )
    op.add_column(
        'bookings',
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
    )
    op.add_column(
        'prices',
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'updated_at')
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookable_units', 'updated_at')
    # ### end Alembic commands ###
