"""Initial migration

Revision ID: 11e57ae7f10c
Revises:
Create Date: 2026-03-27 12:32:56.008570

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e57ae7f10c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bookable_units',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('count_available_bookings', sa.Integer(), nullable=True),
        sa.Column('count_optional_bookings', sa.Integer(), nullable=True),
        sa.Column('feature_bedrooms', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_bookable_units_date'), 'bookable_units', ['date'], unique=False
    )
    op.create_index(
        op.f('ix_bookable_units_product_id'),
        'bookable_units',
        ['product_id'],
        unique=False,
    )
    op.create_table(
        'bookings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=True),
        sa.Column('bookable_unit_id', sa.Integer(), nullable=True),
        sa.Column('booking_creation_date', sa.Date(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('gross_revenue', sa.Float(), nullable=True),
        sa.Column('net_revenue', sa.Float(), nullable=True),
        sa.Column('discount_amount', sa.Float(), nullable=True),
        sa.Column('base_currency', sa.String(), nullable=True),
        sa.Column('booking_nights', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['bookable_unit_id'], ['bookable_units.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table(
        'prices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bookable_unit_id', sa.Integer(), nullable=True),
        sa.Column('current_price', sa.Float(), nullable=True),
        sa.Column('length_of_stay', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['bookable_unit_id'], ['bookable_units.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_bookable_units_product_id'), table_name='bookable_units')
    op.drop_index(op.f('ix_bookable_units_date'), table_name='bookable_units')
    op.drop_table('bookable_units')
    # ### end Alembic commands ###
