"""add missing col date

Revision ID: 66b26338e510
Revises: fc5f966f74e9
Create Date: 2026-03-30 13:31:13.023620

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b26338e510'
down_revision: str | Sequence[str] | None = 'fc5f966f74e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staging_prices', sa.Column('date', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staging_prices', 'date')
    # ### end Alembic commands ###
