"""setup

Revision ID: b213e2ad3693
Revises:
Create Date: 2026-03-30 11:26:37.617300

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b213e2ad3693'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'staging_bookings',
        sa.Column('id', sa.BigInteger(), nullable=True),
        sa.Column('bkg_id', sa.BigInteger(), nullable=True),
        sa.Column('cust_id', sa.BigInteger(), nullable=True),
        sa.Column('product_id', sa.String(), nullable=True),
        sa.Column('date', sa.Integer(), nullable=True),
        sa.Column('booking_creation_date', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('cancellation_date', sa.Float(), nullable=True),
        sa.Column('gross_revenue', sa.Float(), nullable=True),
        sa.Column('net_revenue', sa.Float(), nullable=True),
        sa.Column('discount_amount', sa.Float(), nullable=True),
        sa.Column('base_currency', sa.String(), nullable=True),
        sa.Column('bkg_nights', sa.Integer(), nullable=True),
        sa.Column('feature_1', sa.String(), nullable=True),
        sa.Column('feature_2', sa.String(), nullable=True),
        sa.Column('id_new', sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.PrimaryKeyConstraint('id_new'),
    )
    op.create_index(
        op.f('ix_staging_bookings_date'), 'staging_bookings', ['date'], unique=False
    )
    op.create_index(
        op.f('ix_staging_bookings_product_id'),
        'staging_bookings',
        ['product_id'],
        unique=False,
    )
    op.create_table(
        'staging_capacity',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('product_id', sa.String(), nullable=True),
        sa.Column('calendar_date', sa.Integer(), nullable=True),
        sa.Column('is_bookable', sa.Integer(), nullable=True),
        sa.Column('is_option', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_staging_capacity_id'), 'staging_capacity', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_staging_capacity_product_id'),
        'staging_capacity',
        ['product_id'],
        unique=False,
    )
    op.create_table(
        'staging_prices',
        sa.Column('id', sa.String(), nullable=True),
        sa.Column('product_id', sa.String(), nullable=True),
        sa.Column('date', sa.Integer(), nullable=True),
        sa.Column('current_price', sa.Float(), nullable=True),
        sa.Column('length_of_stay', sa.String(), nullable=True),
        sa.Column('id_new', sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.PrimaryKeyConstraint('id_new'),
    )
    op.create_index(
        op.f('ix_staging_prices_id'), 'staging_prices', ['id'], unique=False
    )
    op.create_table(
        'bookable_units',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('product_id', sa.String(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('count_available_bookings', sa.Integer(), nullable=True),
        sa.Column('count_optional_bookings', sa.Integer(), nullable=True),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_bookable_units_date'), 'bookable_units', ['date'], unique=False
    )
    op.create_index(
        op.f('ix_bookable_units_product_id'),
        'bookable_units',
        ['product_id'],
        unique=False,
    )
    op.create_table(
        'bookings',
        sa.Column('booking_id', sa.BigInteger(), nullable=True),
        sa.Column('bookable_unit_id', sa.String(), nullable=True),
        sa.Column('booking_creation_date', sa.Date(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('gross_revenue', sa.Float(), nullable=True),
        sa.Column('net_revenue', sa.Float(), nullable=True),
        sa.Column('discount_amount', sa.Float(), nullable=True),
        sa.Column('base_currency', sa.String(), nullable=True),
        sa.Column('booking_nights', sa.Integer(), nullable=True),
        sa.Column('feature_bedrooms', sa.Integer(), nullable=True),
        sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_bookings_bookable_unit_id'),
        'bookings',
        ['bookable_unit_id'],
        unique=False,
    )
    op.create_table(
        'prices',
        sa.Column('bookable_unit_id', sa.String(), nullable=True),
        sa.Column('current_price', sa.Float(), nullable=True),
        sa.Column('length_of_stay', sa.String(), nullable=True),
        sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_prices_bookable_unit_id'), 'prices', ['bookable_unit_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_bookable_unit_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_bookings_bookable_unit_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_bookable_units_product_id'), table_name='bookable_units')
    op.drop_index(op.f('ix_bookable_units_date'), table_name='bookable_units')
    op.drop_table('bookable_units')
    op.drop_index(op.f('ix_staging_prices_id'), table_name='staging_prices')
    op.drop_table('staging_prices')
    op.drop_index(op.f('ix_staging_capacity_product_id'), table_name='staging_capacity')
    op.drop_index(op.f('ix_staging_capacity_id'), table_name='staging_capacity')
    op.drop_table('staging_capacity')
    op.drop_index(op.f('ix_staging_bookings_product_id'), table_name='staging_bookings')
    op.drop_index(op.f('ix_staging_bookings_date'), table_name='staging_bookings')
    op.drop_table('staging_bookings')
    # ### end Alembic commands ###
