"""Add staging models

Revision ID: ea1967cadeaf
Revises: 0f367b918bba
Create Date: 2026-03-28 17:20:46.587771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1967cadeaf'
down_revision: Union[str, Sequence[str], None] = '0f367b918bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staging_bookings',
    sa.Column('id_new', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('bkg_id', sa.Integer(), nullable=True),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('booking_creation_date', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('cancellation_date', sa.Float(), nullable=True),
    sa.Column('gross_revenue', sa.Float(), nullable=True),
    sa.Column('net_revenue', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=True),
    sa.Column('bkg_nights', sa.Integer(), nullable=True),
    sa.Column('feature_1', sa.String(), nullable=True),
    sa.Column('feature_2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_new')
    )
    op.create_index(op.f('ix_staging_bookings_id_new'), 'staging_bookings', ['id_new'], unique=False)
    op.create_table('staging_capacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('calendar_date', sa.Integer(), nullable=True),
    sa.Column('is_bookable', sa.Integer(), nullable=True),
    sa.Column('is_option', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_capacity_id'), 'staging_capacity', ['id'], unique=False)
    op.create_table('staging_prices',
    sa.Column('id_new', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('length_of_stay', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_new')
    )
    op.create_index(op.f('ix_staging_prices_id_new'), 'staging_prices', ['id_new'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staging_prices_id_new'), table_name='staging_prices')
    op.drop_table('staging_prices')
    op.drop_index(op.f('ix_staging_capacity_id'), table_name='staging_capacity')
    op.drop_table('staging_capacity')
    op.drop_index(op.f('ix_staging_bookings_id_new'), table_name='staging_bookings')
    op.drop_table('staging_bookings')
    # ### end Alembic commands ###
