"""change id name

Revision ID: ea1dc3a8f662
Revises: eafb2fecd0f4
Create Date: 2026-03-30 20:44:31.510074

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = 'ea1dc3a8f662'
down_revision: str | Sequence[str] | None = 'eafb2fecd0f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
