"""add recommendation model

Revision ID: eafb2fecd0f4
Revises: 66b26338e510
Create Date: 2026-03-30 16:42:50.078499

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eafb2fecd0f4'
down_revision: str | Sequence[str] | None = '66b26338e510'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'recommendations',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('product_id', sa.String(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('count_available_bookings', sa.Integer(), nullable=True),
        sa.Column('count_optional_bookings', sa.Integer(), nullable=True),
        sa.Column('total_available_bookings', sa.Integer(), nullable=True),
        sa.Column('max_capacity', sa.Integer(), nullable=True),
        sa.Column('occupancy_rate', sa.Float(), nullable=True),
        sa.Column('days_until_start', sa.Integer(), nullable=True),
        sa.Column('days_factor', sa.Float(), nullable=True),
        sa.Column('price_adjustment_pct', sa.Float(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_recommendations_date'), 'recommendations', ['date'], unique=False
    )
    op.create_index(
        op.f('ix_recommendations_product_id'),
        'recommendations',
        ['product_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_product_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_date'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
