"""cleaning

Revision ID: fc5f966f74e9
Revises: b213e2ad3693
Create Date: 2026-03-30 13:27:16.317035

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5f966f74e9'
down_revision: str | Sequence[str] | None = 'b213e2ad3693'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staging_prices', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'staging_prices',
        sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
